# Generated by Django 2.1.3 on 2018-12-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20181223_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_full_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
