# Generated by Django 2.1.3 on 2018-12-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181226_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_url',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
